name: ci_build_wheel

on:
  pull_request:

jobs:
  build_py_wheel:
    runs-on: self-hosted

    steps:
      - name: clean space
        run: |
          docker run \
            -v $PWD:/checkout \
            --rm \
            paddlepaddle/paddle:2.5.1-dev-ipu \
            bash -c "cd /checkout && pwd && ls -a /checkout && rm -rf ..?* .[!.]* *"

      - uses: actions/checkout@v2

      - name: build
        run: |
          docker run \
            --ulimit memlock=-1:-1 --net=host --cap-add=IPC_LOCK \
            --device=/dev/infiniband/ --ipc=host \
            -v /tmp:/host_tmp \
            -v $PWD:/checkout \
            -v paddle_ccache:/paddle_ccache \
            -e CCACHE_DIR=/paddle_ccache \
            -e CCACHE_MAXSIZE=20G \
            -v paddle_ipuof:/ipuof \
            -e GITHUB_SHA=${GITHUB_SHA} \
            -v paddle_wheels:/paddle_wheels \
            -e IPUOF_CONFIG_PATH=/ipuof/ipu.conf \
            -e POPLAR_IPUMODEL=1 \
            --workdir /checkout \
            --rm \
            paddlepaddle/paddle:2.5.1-dev-ipu \
            bash /checkout/paddle/scripts/ipu/github_action/action_build_and_test.sh
