name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: self-hosted

    steps:
      - name: clean space
        run: |
          docker run \
            -v $PWD:/checkout \
            --rm \
            paddlepaddle/paddle:2.5.1-dev-ipu \
            bash -c "cd /checkout && pwd && ls -a /checkout && rm -rf ..?* .[!.]* *"

      # 由于 host git 版本太低, 使用 actions/checkout@v2 时得到的不是 git repo
      - uses: actions/checkout@v1

      - id: file_changes
        uses: gglin001/file-changes-action@v1.2.4
        with:
          prNumber: ${{ github.event.number }}
          output: " "

      - name: cache changes
        run: |
          echo "${{ steps.file_changes.outputs.files }}" > $PWD/pr_changed_files.txt

      - name: build
        run: |
          docker run \
            -v $PWD:/checkout \
            -e PR_CHANGED_FILES=/checkout/pr_changed_files.txt \
            --workdir /checkout \
            --rm \
            paddlepaddle/paddle:2.5.1-dev-ipu \
            bash /checkout/paddle/scripts/ipu/github_action/pre-commit.sh
