# auto sync PaddlePaddle/Paddle:develop to develop and create pr to develop-ipu
# ref: https://github.com/repo-sync/repo-sync

on:
  schedule:
    - cron: "0 19 * * *" # 3:00 AM UTC+08:00 everyday
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: self-hosted
    steps:
      - name: clean space
        run: |
          docker run \
            -v $PWD:/checkout \
            --rm \
            paddle_ipu_ci:2.3.0 \
            bash -c "cd /checkout && pwd && ls -a /checkout && rm -rf ..?* .[!.]* *"

      # TODO use latest git version and actions/checkout@v2
      - uses: actions/checkout@v1

      - name: repo-sync
        uses: gglin001/github-sync@v2
        with:
          source_repo: "PaddlePaddle/Paddle"
          source_branch: "develop"
          destination_branch: develop_${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: set date env variable
        run: echo "PR_DATE=$(date --rfc-3339=seconds)" >> $GITHUB_ENV

      - uses: gglin001/pull-request@v2
        name: Create pull request
        with:
          source_branch: develop_${{ github.sha }}
          destination_branch: develop-ipu
          pr_title: "[AUTO PR] Pulling develop into develop-ipu [${{ env.PR_DATE }}]"
          # pr_body: ":crown: *An automated PR*"
          github_token: ${{ secrets.CI_PAT_GGLIN002 }}
          pr_label: "AUTO PR"

      - name: clean space
        run: |
          docker run \
            -v $PWD:/checkout \
            --rm \
            paddle_ipu_ci:2.3.0 \
            bash -c "cd /checkout && pwd && ls -a /checkout && rm -rf ..?* .[!.]* *"
